// Database related Action types
const DATABASE = {
  DATABASE_REGISTER_DATABASE: "DATABASE_REGISTER_DATABASE",
  DATABASE_START_TIMER: "DATABASE_START_TIMER",
  DATABASE_STOP_TIMER: "DATABASE_STOP_TIMER",
};

// Messages related action types
const MESSAGES = {
  MESSAGES_INFO: "MESSAGES_INFO",
  MESSAGES_WARNING: "MESSAGES_WARNING",
  MESSAGES_ERROR: "MESSAGES_ERROR",
  MESSAGES_HIDE_MESSAGE: "MESSAGES_HIDE_MESSAGE",
  MESSAGES_HIDE_ALL_MESSAGES: "MESSAGES_HIDE_ALL_MESSAGES",
  MESSAGES_DELETE_ALL_MESSAGES: "MESSAGES_DELETE_ALL_MESSAGES",
};

const CONFIRM = {
  CONFIRM_DELETE_CONTACT: "CONFIRM_DELETE_CONTACT",
};

const DESIGN = {
  DESIGN_VIEW: "DESIGN_VIEW",
  DESIGN_THEME: "DESIGN_THEME",
};

const WORKLOGS = {
  WORKLOGS_UPDATE: "WORKLOGS_UPDATE",
};

const VIEWSETTINGS = {
  UPDATE_TITLE: "UPDATE_TITLE",
};
const TYPES = {
  ...DATABASE,
  ...MESSAGES,
  ...CONFIRM,
  ...DESIGN,
  ...WORKLOGS,
  VIEWSETTINGS,
};

export {
  TYPES as default,
  DATABASE,
  MESSAGES,
  CONFIRM,
  DESIGN,
  WORKLOGS,
  VIEWSETTINGS,
};
