// Database related Action types
const DATABASE = {
  DATABASE_REGISTER_DATABASE: "DATABASE_REGISTER_DATABASE",
  DATABASE_START_TIMER: "DATABASE_START_TIMER",
  DATABASE_STOP_TIMER: "DATABASE_STOP_TIMER",
};

const DESIGN = {
  DESIGN_VIEW: "DESIGN_VIEW",
  DESIGN_THEME: "DESIGN_THEME",
};

const WORKLOGS = {
  WORKLOGS_UPDATE: "WORKLOGS_UPDATE",
};

const VIEWSETTINGS = {
  UPDATE_TITLE: "UPDATE_TITLE",
};
const TYPES = {
  ...DATABASE,
  ...DESIGN,
  ...WORKLOGS,
  VIEWSETTINGS,
};

export { TYPES as default, DATABASE, DESIGN, WORKLOGS, VIEWSETTINGS };
