const VDESIGN = {
  DESIGN_THEME_DEFAULT: "default",
  DESIGN_THEME_OCEAN: "ocean",
  DESIGN_VIEW_PRIMARY: "primary",
  DESIGN_VIEW_SECONDARY: "secondary"
};

const USERSETTINGS = {
  USERSETTINGS_SELECTED_THEME: "USERSETTINGS_SELECTED_THEME"
};
const VALUES = {
  ...VDESIGN,
  ...USERSETTINGS
};

export { VALUES as default, VDESIGN, USERSETTINGS };
