const TYPES = {
  REGISTER_DATABASE: "REGISTER_DATABASE",
  ADD_NEW_CONTACT: "ADD_NEW_CONTACT",
  HOME: "HOME",
  CONTACTS: "CONTACTS",
  CALENDAR: "CALENDAR",
  SETTINGS: "SETTINGS",
  EDIT_CONTACT: "EDIT_CONTACT",
  SAVE_EDITED_CONTACT: "SAVE_EDITED_CONTACT"
};

export default TYPES;
