// Database related Action types
const DATABASE = {
  DATABASE_REGISTER_DATABASE: "DATABASE_REGISTER_DATABASE",
  DATABASE_ADD_NEW_CONTACT: "DATABASE_ADD_NEW_CONTACT"
};

// Toolbar buttons types and their click events related Action types
const TOOLBAR = {
  TOOLBAR_HOME: "TOOLBAR_HOME",
  TOOLBAR_CONTACTS: "TOOLBAR_CONTACTS",
  TOOLBAR_CALENDAR: "TOOLBAR_CALENDAR",
  TOOLBAR_SETTINGS: "TOOLBAR_SETTINGS",
  TOOLBAR_EDIT_CONTACT: "TOOLBAR_EDIT_CONTACT",
  TOOLBAR_SAVE_EDITED_CONTACT: "TOOLBAR_SAVE_EDITED_CONTACT"
};

// Messages related action types
const MESSAGES = {
  MESSAGES_INFO: "MESSAGES_INFO",
  MESSAGES_WARNING: "MESSAGES_WARNING",
  MESSAGES_ERROR: "MESSAGES_ERROR",
  MESSAGES_HIDE_MESSAGE: "MESSAGES_HIDE_MESSAGE",
  MESSAGES_HIDE_ALL_MESSAGES: "MESSAGES_HIDE_ALL_MESSAGES",
  MESSAGES_DELETE_ALL_MESSAGES: "MESSAGES_DELETE_ALL_MESSAGES"
};

const TYPES = {
  ...DATABASE,
  ...TOOLBAR,
  ...MESSAGES
};

export default TYPES;
